language: node_js
node_js:
  - '8'
  - '9'
  - '10'
install:
  - npm install -g codecov
script:
  - npm install
  - npm run lint
  - npm run test:coverage --runInBand --no-cache
  - npm test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules